" CtrlP Plugin
set runtimepath^=~/.vim/bundle/ctrlp.vim

if executable('rg')
  set grepprg=rg\ --color=never
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
  let g:ctrlp_use_caching = 0
endif
" End

set tabstop=4
set shiftwidth=4
set expandtab
